name: publish-book

on:
  push:
    branches: master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install jupyter-book==0.10.2 ghp-import

    - name: Build the book
      run: |
        python ci/generate_book.py
        jupyter-book build tutorials

    - name: Publish to gh-pages 
      run: |
        ghp-import -n -p -f tutorials/_build/html
